# Generated by Django 4.2 on 2025-07-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='alternative_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
