# Generated by Django 4.2 on 2025-06-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0001_initial'),
        ('order_handling', '0001_initial'),
        ('user_management_system', '0001_initial'),
        ('payment_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management_system.customuser'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_system.payment'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product'),
        ),
    ]
