# Generated by Django 4.2 on 2025-07-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='name ',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='alternative_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='seller',
            name='postal_code',
            field=models.IntegerField(default=0, verbose_name=6),
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='seller',
            name='business_address',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='seller',
            name='business_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst_number',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
