# Generated by Django 4.2 on 2025-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_system', '0002_rename_first_name_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(default='active', max_length=15),
        ),
    ]
